eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

microservice: 
  restaurant-service: 
    endpoints:
      fetchOrderById:
        uri: http://RESTAURANT-SERVICE/restaurant/orders/status/



test:
  input: 50000


logging:
  file:
    name: G:\Electronic_Store\backend\javatechie\microservices\spring-cloud-gateway-jwt-security\app-logs-file\ecom.log
